apiVersion: apps/v1
kind: Deployment
metadata:
  name: compendium-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compendium-app
  template:
    metadata:
      labels:
        app: compendium-app
    spec:
      containers:
      # DB
      - name: compendium-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: compendium-secrets
              key: DB_POSTGRES_PASSWORD
        resources:
          limits:
            cpu: "0.5"
            memory: "4Gi"
          requests:
            cpu: "0.5"
            memory: "4Gi"
        volumeMounts:
        - name: database-volume
          mountPath: /var/lib/postgresql/data
      # BFF
      - name: compendium-bff
        image: ghakondratsky/compendium-bff
        ports:
        - containerPort: 3000
        env:
        - name: BFF_PORT
          value: "3000"
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: compendium-secrets
              key: DB_CONNECTION_STRING
        - name: SSL_PRIVATE_KEY_PATH
          value: "/etc/letsencrypt/live/srv468157.hstgr.cloud/privkey.pem"
        - name: SSL_PUBLIC_CERT_PATH
          value: "/etc/letsencrypt/live/srv468157.hstgr.cloud/fullchain.pem"
        resources:
          limits:
            cpu: "0.5"
            memory: "3Gi"
          requests:
            cpu: "0.5"
            memory: "3Gi"
      
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: compendium-persistent-volume-claim

