apiVersion: v1
kind: PersistentVolume
metadata:
  name: compendium-persistent-volume
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # security is in my nature
    path: /root/database
