apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: compendium-issuer
  namespace: default
spec:
  acme:
    email: aleksandrkondratskii@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: compendium-tls-secret
    solvers:
    - http01:
        ingress:
          name: compendium-ingress

