apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: compendium-sc
provisioner: rancher.io/local-path
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /root/volume