export const templateRepoResponse = {
    "id": 311525798,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMTE1MjU3OTg=",
    "name": "Web-Dev-For-Beginners",
    "full_name": "microsoft/Web-Dev-For-Beginners",
    "private": false,
    "owner": {
        "login": "microsoft",
        "id": 6154722,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6154722?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/microsoft",
        "html_url": "https://github.com/microsoft",
        "followers_url": "https://api.github.com/users/microsoft/followers",
        "following_url": "https://api.github.com/users/microsoft/following{/other_user}",
        "gists_url": "https://api.github.com/users/microsoft/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/microsoft/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/microsoft/subscriptions",
        "organizations_url": "https://api.github.com/users/microsoft/orgs",
        "repos_url": "https://api.github.com/users/microsoft/repos",
        "events_url": "https://api.github.com/users/microsoft/events{/privacy}",
        "received_events_url": "https://api.github.com/users/microsoft/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "html_url": "https://github.com/microsoft/Web-Dev-For-Beginners",
    "description": "24 Lessons, 12 Weeks, Get Started as a Web Developer",
    "fork": false,
    "url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners",
    "forks_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/forks",
    "keys_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/teams",
    "hooks_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/hooks",
    "issue_events_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/issues/events{/number}",
    "events_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/events",
    "assignees_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/assignees{/user}",
    "branches_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/branches{/branch}",
    "tags_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/tags",
    "blobs_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/languages",
    "stargazers_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/stargazers",
    "contributors_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/contributors",
    "subscribers_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/subscribers",
    "subscription_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/subscription",
    "commits_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/contents/{+path}",
    "compare_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/merges",
    "archive_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/downloads",
    "issues_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/issues{/number}",
    "pulls_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/labels{/name}",
    "releases_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/releases{/id}",
    "deployments_url": "https://api.github.com/repos/microsoft/Web-Dev-For-Beginners/deployments",
    "created_at": "2020-11-10T02:44:00Z",
    "updated_at": "2023-12-25T21:15:25Z",
    "pushed_at": "2023-12-22T03:08:45Z",
    "git_url": "git://github.com/microsoft/Web-Dev-For-Beginners.git",
    "ssh_url": "git@github.com:microsoft/Web-Dev-For-Beginners.git",
    "clone_url": "https://github.com/microsoft/Web-Dev-For-Beginners.git",
    "svn_url": "https://github.com/microsoft/Web-Dev-For-Beginners",
    "homepage": "https://microsoft.github.io/Web-Dev-For-Beginners/",
    "size": 86696,
    "stargazers_count": 78854,
    "watchers_count": 78854,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 12155,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 82,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": true,
    "web_commit_signoff_required": false,
    "topics": [
        "css",
        "curriculum",
        "education",
        "html",
        "javascript",
        "learning",
        "tutorials"
    ],
    "visibility": "public",
    "forks": 12155,
    "open_issues": 82,
    "watchers": 78854,
    "default_branch": "main",
    "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
    },
    "temp_clone_token": "",
    "organization": {
        "login": "microsoft",
        "id": 6154722,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6154722?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/microsoft",
        "html_url": "https://github.com/microsoft",
        "followers_url": "https://api.github.com/users/microsoft/followers",
        "following_url": "https://api.github.com/users/microsoft/following{/other_user}",
        "gists_url": "https://api.github.com/users/microsoft/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/microsoft/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/microsoft/subscriptions",
        "organizations_url": "https://api.github.com/users/microsoft/orgs",
        "repos_url": "https://api.github.com/users/microsoft/repos",
        "events_url": "https://api.github.com/users/microsoft/events{/privacy}",
        "received_events_url": "https://api.github.com/users/microsoft/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "network_count": 12155,
    "subscribers_count": 2678
};
