# only for local development
version: "3.9"
name: "compendium-temple"
services:
  postgres:
    image: postgres
    container_name: compendium-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - 5517:5432 # NB
    volumes:
      - ./.data:/var/lib/postgresql/data