direction: right

cli: "@compendium/cli" {

  Cli {
    shape: class
    start(): void;
  }

  ConfigurationManager {
    shape: class
    -registryUrl: string;
    -isDebug: boolean;
    setRegistryUrl(string): void;
    getRegistryUrl(): string;
    setIsDebug(boolean): void;
    getIsDebug(): boolean;
  }
  
  WorkerVersionManager {
    shape: class
    getIsLatestInstalled(): Promise<boolean>
  }

  AutoUpdater {
    shape: class
    constructor(string, number)
    autoupdate(): Promise<void>
  }

  WorkRunner {
    shape: class
    runTask(): Promise<void>
  }

  Cli -> AutoUpdater
  Cli -> ConfigurationManager
  AutoUpdater -> WorkerVersionManager
}

cli.Cli -> package.Worker


package: "@compendium/worker" {
  Worker {
    shape: class
    start(): Promise<void>
  }
}
