direction: right

cli: CLI {
  
  Updater {
    shape: class
    getCurrentVersion(): string
    getLatestVersion(): string
    update(): void
  }

  Logger {
    shape: class
    log(message: string): void
  }

  Runner {
    shape: class
    start(): Promise<void>
    stop(): Promise<void>
  }

  Runner -> IClientWorker

  IClientWorker: <IClientWorker> { shape: class }
}


package: npm package {
  ClientWorker {
    shape: class
    runTask(): Promise<void>
  }
}

cli.IClientWorker -- package.ClientWorker