on:
  pull_request:
  push:
    branches:
      - main

name: "CI/CD"

permissions:
  contents: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN}}

jobs:
  review:
    name: "CI/CD Job"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG_BASE64 }}
          kubectl-version: v1.28.3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # library check
      - name: Install
        run: npm ci
      
      - name: Prisma
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: db:client
          projects: compendium-temple

      - name: Lint
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: list

      - name: Test
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: test
          projects: server,cli,worker

      - name: Build
        env:
          NODE_ENV: production
          WEBSITE_API_URL: http://89.116.38.231:3000/api
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build

      - name: Docker Build
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: docker:build
          projects: bff

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        if: github.event_name == 'push'
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: docker:push
          projects: bff

      - name: Deploy API
        if: github.event_name == 'push'
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: deploy
          projects: compendium-temple

      - name: Deploy Website
        if: github.event_name == 'push' && ${{ hashFiles('dist/packages/website') != '' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist/packages/website
        