name: Create K8s Secrets

on:
  workflow_dispatch:

jobs:
  create-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: K8s Secrets
        run: |
          kubectl delete secret compendium-secrets
          kubectl create secret generic compendium-secrets \
            --from-literal='DB_POSTGRES_PASSWORD=${{ secrets.DB_POSTGRES_PASSWORD }}' \
            --from-literal='DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}' \
            --from-literal='SERVER_AUTH_TOKEN_HASH_SALT=${{ secrets.SERVER_AUTH_TOKEN_HASH_SALT }}'
